## Client Service
apiVersion: v1
kind: Service
metadata:
  name: devops-blog-client-svc
  namespace: default
spec:
  selector:
    app: devops-blog-client
  ports:
    - name: http # Bắt buộc có name để ServiceMonitor (Phase 2) có thể reference
      protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
---
## Server Service
apiVersion: v1
kind: Service
metadata:
  name: devops-blog-server-svc
  namespace: default
spec:
  selector:
    app: devops-blog-server
  ports:
    - name: http # Bắt buộc có name để ServiceMonitor (Phase 2) có thể reference
      protocol: TCP
      port: 80
      targetPort: 3001
  type: ClusterIP
