apiVersion: v1
kind: Service
metadata:
  name: devops-blog-service
  namespace: default
spec:
  selector:
    app: devops-blog-client # Phải khớp với label ở file deployment
  ports:
    - protocol: TCP
      port: 80       # Port mở ra bên ngoài (truy cập web bằng port này)
      targetPort: 3000 # Port bên trong container
  type: NodePort # Dùng NodePort để dễ test trên máy local/VPS lẻ